---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
```



```{r}
data <- read.csv("C:/Users/kzorina/Studing/MMDS/FutureOfWikipedia/data/df_all_with_timestamps.csv", encoding = "UTF-8")
data
```

```{r}
cleaned_data <- data %>% 
  mutate(Ukr_time = as.POSIXct(uk_timestamp, format = "b'%Y%m%d%H%M%S'"),
         Eng_time = as.POSIXct(en_timestamp, format = "b'%Y%m%d%H%M%S'")) %>% 
  mutate(Time_to_translation = as.difftime(Eng_time-Ukr_time, units = "secs")) %>% 
  mutate(Time_to_translation_days = as.integer(as.numeric(Time_to_translation, units = "days"))) %>% 
  mutate(Time_to_translation_hours = as.integer(as.numeric(Time_to_translation, units = "hours"))) %>% 
  select(uk_id,uk_title, en_id, en_title, Ukr_time, Eng_time, Time_to_translation_hours, Time_to_translation_days)
cleaned_data
```

```{r}
ukr_early_eng <- na.omit(cleaned_data[cleaned_data$Time_to_translation_hours > 0,])
ukr_early_eng
```


```{r}
na_DF <- cleaned_data[is.na(cleaned_data$Time_to_translation_days),]
na_DF
```


```{r}
library(pracma)
hist(ukr_early_eng$Time_to_translation_days, 
     breaks=linspace(min(ukr_early_eng$Time_to_translation_days)-0.5, max(ukr_early_eng$Time_to_translation_days)+0.5, n = 70),
     main = "Time before translation (days)",
     col = "#66A4A5",
     xlab = "Days from Ukr page creation to Eng page creation",
     ylab = "Amount of such pages")
```



```{r}
linspace(min(ukr_early_eng$Time_to_translation_days)-0.5, max(ukr_early_eng$Time_to_translation_days)+0.5, n = 70)
peak_data <- ukr_early_eng[ukr_early_eng$Time_to_translation_days > 739 & ukr_early_eng$Time_to_translation_days < 807,]
```


```{r}
peak_data
library(ggplot2)
library(plotly)
g <- ggplot() +
  geom_point(data = peak_data, 
             aes(x = Ukr_time, 
                 y = Time_to_translation_days, 
                 text =      paste("time:", strftime(Ukr_time, format="%Y-%m-%d %H:%M:%S"), 
                                   "eng translation:",Eng_time
                                   #,"page title:",eval(parse(uk_title))
                                   )), col = "red", shape = 4,  size = 1)+
  labs(x = "Creation date of Ukr page", y = "Days from Ukr page creation to Eng page creation")

p = ggplotly(g);
p
```

```{r}
save <- peak_data[peak_data$Ukr_time>"2012-10-04" & peak_data$Ukr_time<"2012-12-30",]
write.csv(save,"C:/Users/kzorina/Studing/MMDS/FutureOfWikipedia/data/save.csv")
```

